# Generated by Django 3.2.6 on 2021-09-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clname', models.CharField(max_length=100)),
                ('clemail', models.EmailField(max_length=40)),
                ('clmob', models.CharField(max_length=20)),
                ('cladd', models.TextField(max_length=400)),
                ('compname', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('clpassword', models.CharField(max_length=100)),
                ('role', models.CharField(default='client', max_length=50)),
            ],
        ),
    ]
