# Generated by Django 3.2.7 on 2021-09-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdname', models.CharField(max_length=300)),
                ('pdprice', models.IntegerField(default=25)),
                ('pddis', models.TextField(max_length=2000)),
                ('pdimage', models.FileField(blank=True, null=True, upload_to='pdimage')),
            ],
        ),
    ]
