# Generated by Django 3.2.6 on 2021-10-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='urole',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
